In [1]:
#try json encoding on the data
from typing import *
import json

class CustomJSONEncoder(json.JSONEncoder):
    def default(self, o: Any) -> Any:
        if isinstance(o, (int, bool, str, float)):
            return o
        elif o is None:
            return None
        elif isinstance(o, dict):
            return o
        elif isinstance(o, list):
            return o
        elif isinstance(o, tuple):
            return {"_type": "tuple", "data": list(o)}
        elif isinstance(o, set):
            return {"_type": "set", "data": list(o)}
        elif isinstance(o, pd.DataFrame):
            return {"_type": "dataframe", "data": o.to_dict()}
        elif isinstance(o, np.ndarray):
            return {"_type": "ndarray", "data": o.tolist()}
        else:
            return super().default(o)

def encode_result(data: Any) -> str:
    return json.dumps(data, cls=CustomJSONEncoder)

In [6]:
import pandas as pd
filename = "/Users/Alessa/Desktop/Econ370/provisions_project/provisions-data/ECON370-provisions-items.csv"
df = pd.read_csv(filename)
df.head()

,date,time,gross.sales,discount,net.sales,gift.card,tax,amt.total,amt.card,amt.cash,amt.gift.card,amt.other,fees,amt.net,card.type,items,customer.id,first.name,discount.type
0,2023-12-31,17:22:11,36.0,0.0,36.0,0,0.0,36.0,36.0,0.0,0.0,0,-1.00,35.00,MasterCard,Singlecut Beersmiths Dry-Hopped Dry Ale 4pk Ca...,38MJ6BKS8P9A0FBAGXBH8QRS0R,NaN,NaN
1,2023-12-31,17:17:50,39.0,0.0,39.0,0,0.0,39.0,39.0,0.0,0.0,0,-1.08,37.92,MasterCard,Maestri Salame Rustico (Regular) Sweetbrook Fa...,A9YGVF3G2H5478AE3A9CZPXM2G,Brandie,NaN
2,2023-12-31,17:13:49,231.0,0.0,231.0,0,0.0,231.0,231.0,0.0,0.0,0,-5.88,225.12,MasterCard,Brewer's Crackers - Everything Flatbread Crack...,S2XATVHGMN4H71KT3D30ZSB4MC,Peter,NaN
3,2023-12-31,17:03:46,40.0,0.0,40.0,0,0.0,40.0,40.0,0.0,0.0,0,-1.10,38.90,Visa,Nero di Cio Lambrusco (Regular) Flora Rosato (...,ZF58GPHRWACSBSTJS4N3CYP8XG,NaN,NaN
4,2023-12-31,16:57:11,34.0,0.0,34.0,0,0.0,34.0,34.0,0.0,0.0,0,-0.95,33.05,MasterCard,9 Di Dante Inferno Vermouth (Regular) - Bin 231,R0XCHCVGVXVJ0S1T6J9PANZF8M,NaN,NaN

In [9]:
json_data = encode_result(df)
with open('/Users/Alessa/Desktop/Econ370/provisions_project/output_file.json', 'w') as json_file:
    json_file.write(json_data)

print("JSON file saved successfully!")

JSON file saved successfully!